[package]
name = "pacbot_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pacbot_rs"
crate-type = ["cdylib"]

[dependencies]
arrayvec = "0.7.2"
num_enum = "0.5.11"
pyo3 = "0.18.1"
rand = "0.8.5"
