name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
    - uses: actions/checkout@v2
    - uses: snok/install-poetry@v1
    - name: Install Poetry dependencies
      run: poetry install
    - name: Build Rust module
      run: poetry run --directory .. -- maturin develop
      working-directory: ./pacbot_rs
    - name: Run tests
      run: poetry run pytest tests
